### ISSUE TITLE
No way to set path of .swiftlint.yml  file?

### ISSUE THREAD

**Issue by amichail** [AtomLinter/linter-swiftlint#11]
Sometimes this is in a different directory from the source files being edited in Atom.

How can one set the path of this file?

**Comment by norio-nomura** [comment]
You can set configuration path as following:
<img width="809" alt="screenshot 2016-01-20 00 18 13" src="https://cloud.githubusercontent.com/assets/33430/12422658/618ab78c-bf0b-11e5-8af2-856e7306776b.png">
