### ISSUE TITLE
Install without language-swift

### ISSUE THREAD

**Issue by hex2010** [AtomLinter/linter-swiftlint#39]
Maybe it is not a real issue, but i consider the `linter-swiftlint`  should not depends on `language-swift` package.  because some other packages may provide the `source.swift` as well.

how can I make it depends on `source.swift` grammar instead of `language-swift` package?

**Comment by Arcanemagus** [comment]
Unfortunately Atom's package management system currently isn't smart enough for any more advanced solution. If you would rather `language-swift` isn't used, simply disable it as this only ensures that it is _installed_, not active.
